config/routes.rb
Rails.application.routes.draw do

  get 'static_page/home'
  get 'static_page/help'

  root 'users#settings'

  match 'search_food', to: 'foods#search', via: :get, as: :foods_search

  devise_for :users, :controllers => { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    member do
      get 'settings'
    end
  end

  resources :ingredients

  resources :weights

  resources :allergens, except: [:destroy, :update]

  resources :foods

  resources :diary_entries do
    collection do
      get 'sort/:field' => 'diary_entries#sort'
    end
  end

  post 'diary_entries/download'

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%=image_tag "1.jpg" %>
    </div>
    <div class="item">
      <%=image_tag "2.jpg" %>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/static_page/help.html.erb
<h1>This is a help page!</h1>
<p>Find me in app/views/static_page/help.html.erb</p>

app/views/static_page/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home | Food Allergies</title>
  </head>
  <body>

  <div class="center jumbotron">

  <%= render 'carousel' %>
  <h1>
    Welcome to the Food Allergies Tracker <br>
    <small>We help you manage your health!<br>
    <%= current_user.username %></small>
  </h1>
  <br>
  <div class="row">
    <div class="col-sm-6 col-md-3">
      <h2 class="glyphicon glyphicon-list-alt"></h2>
      <h4><%= link_to "My Food Diary", diary_entries_path, class: "thumbnail" %></h4>
      </div>
    <div class="col-sm-6 col-md-3">
      <h2 class="glyphicon glyphicon-search"></h2>
      <h4><%= link_to "Look up Food", foods_search_path, class: "thumbnail" %></h4>
    </div>
    <div class="col-sm-6 col-md-3">
      <h2 class="glyphicon glyphicon-pencil"></h2>
      <h4><%= link_to "Add Food", foods_path, class: "thumbnail" %></h4>
    </div>
    <div class="col-sm-6 col-md-3">
      <h2 class="glyphicon glyphicon-option-horizontal"></h2>
      <h4><%= link_to "Weight Tracker", weights_path, class: "thumbnail" %></h4>
    </div>
  </div>

  <% if current_user.admin? %>
  <h4><%= link_to "Check Patients Info", users_path, class: "thumbnail" %></h4>
  <% end %>

  </div>


  </body>

</html>