config/routes.rb
Rails.application.routes.draw do

  get 'static_page/home'
  get 'static_page/help'

  root 'users#settings'

  match 'search_food', to: 'foods#search', via: :get, as: :foods_search

  devise_for :users, :controllers => { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    member do
      get 'settings'
    end
  end

  resources :ingredients

  resources :weights

  resources :allergens, except: [:destroy, :update]

  resources :foods

  resources :diary_entries do
    collection do
      get 'sort/:field' => 'diary_entries#sort'
    end
  end

  post 'diary_entries/download'

end

app/models/food.rb
# == Schema Information
#
# Table name: foods
#
#  id              :integer          not null, primary key
#  name            :string
#  product_barcode :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Food < ActiveRecord::Base
	validates :name, :presence => true
	has_and_belongs_to_many :ingredients
	has_many :allergens , through: :ingredients

	validates_each :name do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end

end

app/controllers/foods_controller.rb
#require 'pry'
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    if @food != nil
      @ingredients = FoodApi.retrieve_results(@food.name)
      @ingredients.map(&:capitalize).each do |ingredient|
        ingredient = Ingredient.find_or_create_by(name: ingredient)
        @food.ingredients << ingredient unless @food.ingredients.include? ingredient
      end      
    end
  end

  def search

    myAllergens = Array.new   # get allergens of the user
    @result = Array.new
    @foodAllergens = Array.new
    if params[:search] != nil
      foodname = params[:search]
    end

    if foodname != nil and foodname != ""
      User.find(current_user.id).allergens.each do |a|
        myAllergens << a.name
      end

      ingredients = FoodApi.retrieve_results(foodname)
      if ingredients.empty?
        @result << "Unknown"
        return @result
      end
      ingredients.map(&:capitalize).each do |ingredient|
        ingredient = Ingredient.find_or_create_by(name: ingredient)
        ingredient.allergens.each do |a|
          @foodAllergens << a.name
          if myAllergens.include? a.name
            @result << a.name
          end
        end
      end
      @result.uniq!
      @foodAllergens.uniq!
    end
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        # binding.pry
        # @food.add_allergen(params[:food][:allergen_ids])
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #something is modified here
    def food_params
      params.require(:food).permit(:name, :product_barcode)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :product_barcode %><br>
    <%= f.text_field :product_barcode %>
  </div>
  <div class="field">
    <%= f.label :ingredient_id %><br>
    <%= collection_select :food, :ingredient_ids, Ingredient.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Food Database</h1>

<table class="table table-responsive">

  <thead>
    <tr>
      <th>Food</th>
      <th>Product barcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.product_barcode %></td>
        <td><%= link_to 'Show', food, class: "btn btn-success btn" %></td>
        <td><%= link_to 'Edit', edit_food_path(food), class: "btn btn-warning"%></td>
        <td><%= link_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add food', new_food_path, class: "btn btn-success btn-lg"%>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/search.html.erb
<h1> Food Search Page </h1>
<h4> Please enter the food of interest to see its allergens </h4>
<%= form_tag foods_search_path, :method => 'get' do%>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Search" %>
<% end %>

<table>


<% if @foodAllergens != nil %>
  <thead>
    <tr>
      <% if @foodAllergens.size != 0 %>
        <% if @foodAllergens.size > 1 %>
          <th> Allergens contained in this food that you are searching: </th>
        <% else %>
          <th> Allergen contained in this food that you are searching: </th>
        <% end %>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @foodAllergens.each do |x| %>
  <tr>
    <td>
    <%= x %>
    </td>
  </tr>
    <% end %>
  <% else %>
    <%= @message %>
  <% end %>
</tbody>
</table>

<table>
  <thead>
    <tr>
      <% if @result.size != 0 %>
        <% if @result.size > 1 %>
          <th style="color:blue;"> Allergens in this food that you are
             allergic to: </th>
        <% else %>
          <th style="color:blue;"> Allergen in this food that you are
           allergic to: </th>
        <% end %>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @result.each do |x| %>
  <tr>
    <td style="color:red;">
    <%= x %>
    </td>
  </tr>
    <% end %>
</tbody>
</table>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Product barcode:</strong>
  <%= @food.product_barcode %>
</p>

<p>
  <strong>Ingredients:</strong>
  <% @food.ingredients.uniq.each do |ingredient| %>
      <p><%= ingredient.name %></p>
  <% end %>

</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>