config/routes.rb
Rails.application.routes.draw do

  get 'static_page/home'
  get 'static_page/help'

  root 'users#settings'

  match 'search_food', to: 'foods#search', via: :get, as: :foods_search

  devise_for :users, :controllers => { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    member do
      get 'settings'
    end
  end

  resources :ingredients

  resources :weights

  resources :allergens, except: [:destroy, :update]

  resources :foods

  resources :diary_entries do
    collection do
      get 'sort/:field' => 'diary_entries#sort'
    end
  end

  post 'diary_entries/download'

end

app/models/diary_entry.rb
# == Schema Information
#
# Table name: diary_entries
#
#  id         :integer          not null, primary key
#  time       :datetime
#  meal       :string
#  food       :string
#  amount     :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class DiaryEntry < ActiveRecord::Base
	validates :food, :presence => true
	validates :amount, numericality: { greater_than: 0 }
	belongs_to :user
end

app/controllers/diary_entries_controller.rb
class DiaryEntriesController < ApplicationController
  before_action :set_diary_entry, only: [:show, :edit, :update, :destroy]

  # GET /diary_entries
  # GET /diary_entries.json
  def index
    @diary_entries = DiaryEntry.where("user_id = ?", current_user.id).order('time')
  end

  # def admin_index
  #   @diary_entries = DiaryEntry.all.order('time')
  # end

  # GET /diary_entries/1
  # GET /diary_entries/1.json
  def show
  end

  # GET /diary_entries/new
  def new
    @diary_entry = DiaryEntry.new
  end

  # GET /diary_entries/1/edit
  def edit
  end

  # return an array of allergens
  def get_allergens(foodname)
    # first seach from local dasebase
    food = Food.find_by_name(foodname.humanize)
    result = Array.new
    myAllergens = Array.new   # get allergens of the user
    User.find(current_user.id).allergens.each do |a|
      myAllergens << a.name
    end

    # if food != nil
    #   allergens = food.allergens  # get allergens of the food
    #   if allergens != nil
    #     allergens.each do |a|
    #       if myAllergens.include? a.name
    #         result << a.name
    #       end
    #     end
    #   end
    # end
    # second, search from API
    ingredients = FoodApi.retrieve_results(foodname)
    if ingredients.empty?
      result << "Unknown"
      return result
    end
    ingredients.map(&:capitalize).each do |ingredient|
      ingredient = Ingredient.find_or_create_by(name: ingredient)
      ingredient.allergens.each do |a|
        if myAllergens.include? a.name
          result << a.name
        end
      end
    end
    return result.uniq
  end
  helper_method :get_allergens

  def sort
    @diary_entries = []
    if (DiaryEntry.attribute_names.include? (params[:field])) then
      @diary_entries = DiaryEntry.where("user_id = ?", current_user.id).order(params[:field])
    end
    
    render :index
  end


  def download
    @diary_entries = DiaryEntry.where("user_id = ?", current_user.id).order('time')
    @user_id = current_user.id
    html = render_to_string(:layout => false , :action => "download.html.erb") # your view erb files goes to :action 
    kit = PDFKit.new(html)
    send_data(kit.to_pdf, :filename=>"#{@user_id}.pdf",
      :type => 'application/pdf', :disposition => 'inline')
  end


  # POST /diary_entries
  # POST /diary_entries.json
  def create
    @diary_entry = DiaryEntry.new(diary_entry_params)
    @diary_entry.user_id = current_user.id

    respond_to do |format|
      if @diary_entry.save
        format.html { redirect_to @diary_entry, notice: 'Diary entry was successfully created.' }
        format.json { render :show, status: :created, location: @diary_entry }
      else
        format.html { render :new }
        format.json { render json: @diary_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diary_entries/1
  # PATCH/PUT /diary_entries/1.json
  def update
    respond_to do |format|
      if @diary_entry.update(diary_entry_params)
        format.html { redirect_to @diary_entry, notice: 'Diary entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary_entry }
      else
        format.html { render :edit }
        format.json { render json: @diary_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diary_entries/1
  # DELETE /diary_entries/1.json
  def destroy
    @diary_entry.destroy
    respond_to do |format|
      format.html { redirect_to diary_entries_url, notice: 'Diary entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary_entry
      @diary_entry = DiaryEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_entry_params
      params.require(:diary_entry).permit(:time, :meal, :food, :amount)
    end
end

app/helpers/diary_entries_helper.rb
module DiaryEntriesHelper
end

app/views/diary_entries/_form.html.erb
<%= form_for (@diary_entry) do |f| %>
  <% if @diary_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diary_entry.errors.count, "error") %> prohibited this diary_entry from being saved:</h2>

      <ul>
      <% @diary_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b>Date and </b> <%= f.label :time %><br>
    <%= f.datetime_select(:time, :minute_step => 5) %>
  </div>
  <div class="field">
    <%= f.label :meal %><br>
    <%= f.select :meal, options_for_select([['Breakfast' ,"Breakfast"], ['Lunch', "Lunch"], ['Dinner', "Dinner"], ['Other', "Other"]])%>
  </div>
  <div class="field">
    <%= f.label :food %> <b>Name</b><br>
    <%= f.text_field :food, required: true%>
  </div>
  <div class="field">
    <%= f.label :amount %> <b>(Serving Size)</b><br>
    <%= f.number_field :amount, class: :text_field, step: :any, required: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/diary_entries/download.html.erb
<center><h1>My Food Diary</h1></center>
<b>Username: <%= current_user.username %><br>
Timestamp: <%= Time.new.strftime("%Y-%m-%d %H:%M:%S") %></b><br>

<table>
  <thead>
    <tr align="center">
      <th width = "20%">Date and Time</th>
      <th width = "20%">Meal</th>
      <th width = "20%">Food Name</th>
      <th width = "20%">Amount (Serving Size)</th>
      <th width = "20%">Allergens?</th>
    </tr>
  </thead>

  <tbody>
    <% @diary_entries.each do |diary_entry| %>
      <tr align="center">
        <td><%= diary_entry.time.to_formatted_s(:short) %></td>
        <td><%= diary_entry.meal %></td>
        <td><%= diary_entry.food %></td>
        <td><%= diary_entry.amount %></td>
        <td>
          <% allergens = get_allergens(diary_entry.food) %>
          <% if allergens.empty? %>
            <font color="green">Free</font>
          <% elsif allergens.length == 1 and allergens[0] == "Unknown" %>
            <font color="orange">Unknown</font>
          <% else %>
            <font color="red">Detected</font>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/diary_entries/edit.html.erb
<h1>Editing Diary Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @diary_entry %> |
<%= link_to 'Back', diary_entries_path %>

app/views/diary_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Food Diary</h1>

<table>
  <thead>
    <tr align="center">
      <th width = "14.4%">Date and Time</th>
      <th width = "14.4%">Meal</th>
      <th width = "14.4%">Food Name</th>
      <th width = "14.4%">Amount (Serving Size)</th>
      <th width = "14.4%">Allergens?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diary_entries.each do |diary_entry| %>
      <tr>
        <td><%= diary_entry.time.to_formatted_s(:short) %></td>
        <td><%= diary_entry.meal %></td>
        <td><%= diary_entry.food %></td>
        <td><%= diary_entry.amount %></td>
        <td>
          <% allergens = get_allergens(diary_entry.food) %>
          <% if allergens.empty? %>
            <font color="green">Free</font>
          <% elsif allergens[0] == "Unknown" %>
            <font color="orange">Unknown</font>
          <% else %>
            <font color="red">Detected</font>
          <% end %>
        </td>
        <td>
          <div class="btn-group btn-group-justified" >
            <%= link_to 'Show', diary_entry, :class => 'btn btn-success btn-xs active' %>
            <%= link_to 'Edit', edit_diary_entry_path(diary_entry), :class => 'btn btn-warning btn-xs active' %>
            <%= link_to 'Delete', diary_entry, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs active' %>
          </div>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="buttom btn-group btn-group-justified">
  <%= link_to 'Add New Entry', new_diary_entry_path, :class => 'btn btn-primary active' %>
  <%= link_to 'Download', diary_entries_download_path, method: :post, :class => 'btn btn-info active' %>
</div>

app/views/diary_entries/new.html.erb
<h1>New Diary Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', diary_entries_path %>

app/views/diary_entries/show.html.erb
<p id="notice"><%= notice %></p>

<% allergens = get_allergens(@diary_entry.food) %>
<% if not allergens.empty? and not allergens[0] == "Unknown" %>
  <div class="alert">
    <strong>WARNING: </strong> Allergens detected! We suggest you not taking this entry.
  </div>
<% end %>

<p>
  <strong>Time:</strong>
  <%= @diary_entry.time %>
</p>

<p>
  <strong>Meal:</strong>
  <%= @diary_entry.meal %>
</p>

<p>
  <strong>Food:</strong>
  <%= @diary_entry.food %>
</p>

<p>
  <strong>Allergens:</strong>
  <% allergens.each do |a| %>
    <font color="red"><%= a %></font>
  <% end %>
</p>

<p>
  <strong>Amount (Serving Size):</strong>
  <%= @diary_entry.amount %>
</p>

<%= link_to 'Edit', edit_diary_entry_path(@diary_entry) %> |
<%= link_to 'Back', diary_entries_path %>